<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>denegado</name>
  <uuid>e4249519-5129-489d-87af-c3ff9b96b734</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[si Decisión es "denegado" entonces imprimir "no es posible" ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
