<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>29c88523-1c0d-4a4c-8f55-cc67f2e0f45d</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[asignar a decisión "denegado" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
